[package]
name = "fetch-oldfaithful"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
jetstreamer-firehose = "0.2.0"
jetstreamer-plugin = "0.2.0"
jetstreamer-utils = "0.2.0"
solana-hash = { version = "3.0.0", features = ["serde"] }
solana-sdk = "2.2.0"
solana-sysvar = { version = "3.0.0", features = ["serde"] }
tokio = {version = "1.48.0", features = ["macros"]}
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
