version: '3.8'

services:
  indexer-1:
    image: myusername/solixdb-indexer:latest
    container_name: indexer-1
    environment:
      - SLOT_START=377107390
      - SLOT_END=377107395
      - THREADS=4
      - CLICKHOUSE_URL=http://clickhouse:8123
      - CLEAR_DB_ON_START=true
    restart: "no"
    networks:
      - indexer-network
      - clickhouse-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

